### ISSUE TITLE
0.17.0 release with some BREAKING CHANGES

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/prettierx#416]
__updated:__

- [x] offsetTernaryExpressions - PR #415 to resolve "Standard JS" ternary formatting issue on the `prettierx` side (issue #41)
- ~~rename `--space-before-function-paren` to something like `--space-after-function-name` to be more consistent with the actual effect on recent `prettierx` releases (similar to <https://eslint.org/docs/rules/space-after-function-name> which was removed from eslint)~~
- ~~possibly rename `--generator-star-spacing` and `--yield-star-spacing`~~
- [x] I am planning to drop `--no-align-ternary-lines` as superseded by the new `offsetTernaryExpressions` feature in PR #415
- [x] ~~possibly~~ rename `--paren-spacing` to `space-in-parens` (similar to <https://eslint.org/docs/rules/space-in-parens>) and split out some functionality into other options (see #426)
- [x] ~~possibly~~ replace `--bracket-spacing` with finer-grained options (see #426)
- [x] add separate options such as `-css-paren-spacing`, etc. to configure paren & curly spacing for CSS

I would like to make this release in the very near future so please raise any possible objections ASAP!

I would also like to drop the outdated option names before merging with Prettier 2.2.1 (#414) which would likely require a rebase due to the amount of code that was moved around in the Prettier code base.

/cc @aMarCruz @sheerun @ai

**Comment by brody2consult** [comment]
Release 0.17.0 with the breaking changes has been published. Please see the updated list in the description or check out the release notes in CHANGELOG.md.
